### ISSUE TITLE
ESP32Box3

### ISSUE THREAD

**Issue by kuzmanzs** [lucasriepe/embeddedProjects#1]
Hi,

I have watched your video, big thanks. I have seen you have driver configuration for ESP32 BOX3 as well, where can I download it? Or  have you created it?

**Comment by lucasriepe** [comment]
Hi, so explicitly not for Box 3 but this one should work on its own.

**Comment by kuzmanzs** [comment]
Hi, I know it is for Waveshare 7". In your video I have seen you also have such configuration for ESP-BOX and ESP Wrover Kit.
How can I get such configs for Squareline Studio?
![squareline](https://github.com/user-attachments/assets/a855a1e3-7882-462b-82d1-09e58099cfc6)

**Comment by kuzmanzs** [comment]
I have resintalled Squareline and now I see the other ESP projects.
